# Generated by Django 4.0.4 on 2022-06-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrdCntrlr', '0002_database_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrade', models.CharField(max_length=3, verbose_name='Новая Оценка')),
            ],
        ),
    ]
