# Generated by Django 4.1.2 on 2023-01-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrdCntrlr', '0003_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='invis_indx',
            field=models.CharField(default='', max_length=3, verbose_name='Индекс agrade'),
        ),
    ]
